#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_TEXTBOXES                           104
#define IDR_MAINMENU                            106
#define IDD_DRAWINGS                            108
#define IDB_BITMAP1                             109
#define IDD_VIEWS                               111
#define IDR_CONTEXTMENU                         115
#define IDR_STDTOOLBAR                          117
#define IDC_CHECKBOX1                           1000
#define IDC_CTXTESTSITE                         1000
#define IDC_CHECKBOX2                           1001
#define IDC_CHECKBOX3                           1002
#define IDC_COMBO2                              1002
#define IDC_COMBO3                              1003
#define IDC_CUSTOM2                             1003
#define IDC_LIST1                               1004
#define IDC_RADIO1                              1004
#define IDC_LIST2                               1005
#define IDC_RADIO2                              1005
#define IDC_MONTHCALENDAR1                      1006
#define IDC_RADIO3                              1006
#define IDC_BUTTON1                             1008
#define IDC_TREE1                               1008
#define IDC_BUTTON2                             1009
#define IDC_PROGRESS1                           1009
#define IDC_BUTTON3                             1010
#define IDC_SCROLLBAR1                          1010
#define IDC_SLIDER1                             1011
#define IDC_PROGRESS2                           1012
#define IDC_SCROLLBAR2                          1013
#define IDC_BUTTON12                            1019
#define IDC_BUTTON13                            1020
#define IDC_BUTTON14                            1021
#define IDC_BUTTON4                             1022
#define IDC_BUTTON5                             1023
#define IDC_BUTTON6                             1024
#define IDC_BUTTON7                             1025
#define IDC_BUTTON8                             1026
#define IDC_BUTTON9                             1027
#define IDC_BUTTON10                            1028
#define IDC_BUTTON11                            1029
#define IDC_BUTTON15                            1030
#define IDC_BUTTON16                            1031
#define IDC_BUTTON17                            1032
#define IDC_COMBO1                              1033
#define IDC_DATETIMEPICKER1                     1034
#define IDC_EDIT1                               1035
#define IDC_HOTKEY1                             1036
#define IDC_IPADDRESS1                          1037
#define IDC_EDIT2                               1038
#define IDC_DATETIMEPICKER2                     1039
#define IDC_DATETIMEPICKER3                     1040
#define IDC_DATETIMEPICKER4                     1041
#define IDC_EDIT3                               1042
#define IDC_EDIT4                               1043
#define IDC_EDIT5                               1044
#define IDC_EDIT6                               1045
#define IDC_EDIT7                               1046
#define IDC_EDIT8                               1047
#define IDC_FILE_EXIT                           40000
#define IDC_HELP_ABOUT                          40001
#define IDC_CUSTOM1                             40002
#define IDC_SLIDER2                             40002
#define IDC_SLIDER3                             40003
#define IDM_ENDING1                             40003
#define IDC_SLIDER4                             40004
#define IDC_SLIDER5                             40005
#define IDC_SLIDER6                             40006
